# Generated by Django 4.0.1 on 2022-01-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Podcasts',
            new_name='Podcast',
        ),
    ]
