# Generated by Django 4.0.1 on 2022-01-21 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_rename_podcasts_podcast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='subject',
        ),
        migrations.AddField(
            model_name='podcast',
            name='producer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='podcast.podcaster'),
        ),
    ]
