# Generated by Django 4.0.1 on 2022-01-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0004_message_alter_podcast_producer'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='text',
            field=models.TextField(null=True, verbose_name='متن'),
        ),
    ]
