# Generated by Django 4.0.1 on 2022-02-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0005_podcast_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='تصویر'),
        ),
    ]
