# Generated by Django 4.0.1 on 2022-02-01 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0006_alter_podcast_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='podcastID',
        ),
    ]
