# Generated by Django 4.0.1 on 2022-02-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0008_podcast_castboxlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='cast',
            field=models.TextField(null=True, verbose_name='عوامل'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='music',
            field=models.TextField(null=True, verbose_name='موسیقی ها'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='publishDate',
            field=models.DateField(auto_now=True, verbose_name='تاریخ'),
        ),
    ]
