# Generated by Django 4.0.1 on 2022-02-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0009_alter_podcast_cast_alter_podcast_music_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='castboxilink',
            field=models.TextField(null=True, verbose_name='لینک آی فریم کست باکس'),
        ),
    ]
